version: '3.8'

services:
  database:
    image: postgres:14
    container_name: rise-of-founders-db
    environment:
      POSTGRES_DB: rise_of_founders_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: rise-of-founders-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@database:5432/rise_of_founders_prod
      JWT_SECRET: ${JWT_SECRET}
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SOLANA_RPC_URL: https://api.devnet.solana.com
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - database
    restart: unless-stopped
    command: npm start

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
        NEXT_PUBLIC_SOLANA_NETWORK: devnet
        NEXT_PUBLIC_HONEYCOMB_PROJECT_ID: ${NEXT_PUBLIC_HONEYCOMB_PROJECT_ID}
    container_name: rise-of-founders-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: rise-of-founders-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data: